### ISSUE TITLE
for the funny

### ISSUE THREAD

**Issue by RedSolarflare** [HoboMechanistic/GameModding#1]
some classics that would all work good as tips:
    Sly Marbo threw a grenade and killed five Orks. Then it exploded.
    Sly Marbo poked the Warp right in the Eye of Terror.
    A Catachan Devil once stung Sly Marbo. After 5 solar days of agonizing pain, the Catachan Devil died.
    Flak Armour wears Sly Marbo for protection.
    Sly Marbo doesn't have a shadow because he scared it off.
    When Ambulls go to bed at night, they check their nests for Sly Marbo.
    The fastest way to a man's heart is with Sly Marbo's blade.
    Sly Marbo once shot down a Dakkajet by pointing at it with his finger and saying "bang!".
    Sly Marbo doesn't shower, he takes blood baths.
    Lord Castellan Ursarkar E. Creed wears Sly Marbo pyjamas.
    If at first you don't succeed, you're not Sly Marbo.
    The official name for Exterminatus is Sly Marbo.
    Sly Marbo beat a Warlord Titan at arm wrestling.
    Sly Marbo hacked a Tyranid Prime to death with its own scything talon.
    Sly Marbo can run faster than a Shokkjump Dragsta.
    Sly Marbo sleeps with a pillow under his gun.
    The Cicatrix Maledictum was created when Sly Marbo sneezed.
    The first name engraved in every suit of Adeptus Custodes' armour is Sly Marbo.
    Sly Marbo does not sleep. He waits...
    Sly Marbo does not go hunting because "hunting" implies the possibility of failure -- Sly Marbo goes killing.
    Roboute Guilliman keeps an inspirational pict of Sly Marbo with him at all times.
    Sly Marbo won a staring contest with a Necron.

**Comment by ChildOfTheCron** [comment]
Thanks for the recommendations :D I'll be adding some of these in with the next batch of lore strings in version v1.0.2

**Comment by ChildOfTheCron** [comment]
Implemented many of these along with some other updates in version 1.0.2.
