### ISSUE TITLE
gamemodding

### ISSUE THREAD

**Issue by LeBaasti** [HoboMechanistic/GameModding#6]
Hey, 
do you still work on game mods?
I could need your help, if you have some time. 
pls add me on Discord LeBaasti | Bastian#3323
Best regards Bastian

**Comment by ChildOfTheCron** [comment]
Hey, sorry but my day-job is currently taking up all of my time so don't have time to work on any mods atm. If you need Darktide help you can find modding folks on the Darktide modding discord at https://discord.gg/GFyCGNpJb8
